In [2]:
import pandas as pd
import numpy as np

In [4]:
df1 = pd.read_csv('./BrentfordStats2014-15.csv')
df2 = pd.read_csv('./BrentfordStats2015-16.csv')
df3 = pd.read_csv('./BrentfordStats2016-17.csv')
df4 = pd.read_csv('./BrentfordStats2017-18.csv')
df5 = pd.read_csv('./BrentfordStats2018-19.csv')
df6 = pd.read_csv('./BrentfordStats2019-20.csv')
df = pd.concat([df1, df2, df3, df4, df5, df6])
df.to_csv('BrentfordStats.csv', index=False)

In [8]:
table201415 = pd.read_csv('./datasets/2014-15 Championship Table.csv')
table201415.drop(['Attendance','Top Team Scorer', 'Goalkeeper', 'Notes'], axis=1, inplace=True)
table201415['Season'] = "2014-15"
table201415

    Rk            Squad  MP   W   D   L  GF  GA  GDiff  Pts   Season
0    1      Bournemouth  46  26  12   8  98  45     53   90  2014-15
1    2          Watford  46  27   8  11  91  50     41   89  2014-15
2    3     Norwich City  46  25  11  10  88  48     40   86  2014-15
3    4    Middlesbrough  46  25  10  11  68  37     31   85  2014-15
4    5        Brentford  46  23   9  14  78  59     19   78  2014-15
5    6     Ipswich Town  46  22  12  12  72  54     18   78  2014-15
6    7           Wolves  46  22  12  12  70  56     14   78  2014-15
7    8     Derby County  46  21  14  11  85  56     29   77  2014-15
8    9        Blackburn  46  17  16  13  66  59      7   67  2014-15
9   10  Birmingham City  46  16  15  15  54  64    -10   63  2014-15
10  11     Cardiff City  46  16  14  16  57  61     -4   62  2014-15
11  12     Charlton Ath  46  14  18  14  54  60     -6   60  2014-15
12  13   Sheffield Weds  46  14  18  14  43  49     -6   60  2014-15
13  14  Nott'ham Forest  46  15  14  17  71  69      2   59  2014-15
14  15     Leeds United  46  15  11  20  50  61    -11   56  2014-15
15  16     Huddersfield  46  13  16  17  58  75    -17   55  2014-15
16  17           Fulham  46  14  10  22  62  83    -21   52  2014-15
17  18           Bolton  46  13  12  21  54  67    -13   51  2014-15
18  19          Reading  46  13  11  22  48  69    -21   50  2014-15
19  20         Brighton  46  10  17  19  44  54    -10   47  2014-15
20  21    Rotherham Utd  46  11  16  19  46  67    -21   46  2014-15
21  22         Millwall  46   9  14  23  42  76    -34   41  2014-15
22  23   Wigan Athletic  46   9  12  25  39  64    -25   39  2014-15
23  24        Blackpool  46   4  14  28  36  91    -55   26  2014-15

In [9]:
table201516 = pd.read_csv('./datasets/2015-16 Championship Table.csv')
table201516.drop(['Attendance','Top Team Scorer', 'Goalkeeper', 'Notes'], axis=1, inplace=True)
table201516['Season'] = "2015-16"
table201516

    Rk            Squad  MP   W   D   L  GF  GA  GDiff  Pts   Season
0    1          Burnley  46  26  15   5  72  35     37   93  2015-16
1    2    Middlesbrough  46  26  11   9  63  31     32   89  2015-16
2    3         Brighton  46  24  17   5  72  42     30   89  2015-16
3    4        Hull City  46  24  11  11  69  35     34   83  2015-16
4    5     Derby County  46  21  15  10  66  43     23   78  2015-16
5    6   Sheffield Weds  46  19  17  10  66  45     21   74  2015-16
6    7     Ipswich Town  46  18  15  13  53  51      2   69  2015-16
7    8     Cardiff City  46  17  17  12  56  51      5   68  2015-16
8    9        Brentford  46  19   8  19  72  67      5   65  2015-16
9   10  Birmingham City  46  16  15  15  53  49      4   63  2015-16
10  11          Preston  46  15  17  14  45  45      0   62  2015-16
11  12              QPR  46  14  18  14  54  54      0   60  2015-16
12  13     Leeds United  46  14  17  15  50  58     -8   59  2015-16
13  14           Wolves  46  14  16  16  53  58     -5   58  2015-16
14  15        Blackburn  46  13  16  17  46  46      0   55  2015-16
15  16  Nott'ham Forest  46  13  16  17  43  47     -4   55  2015-16
16  17          Reading  46  13  13  20  52  59     -7   52  2015-16
17  18     Bristol City  46  13  13  20  54  71    -17   52  2015-16
18  19     Huddersfield  46  13  12  21  59  70    -11   51  2015-16
19  20           Fulham  46  12  15  19  66  79    -13   51  2015-16
20  21    Rotherham Utd  46  13  10  23  53  71    -18   49  2015-16
21  22     Charlton Ath  46   9  13  24  40  80    -40   40  2015-16
22  23          MK Dons  46   9  12  25  39  69    -30   39  2015-16
23  24           Bolton  46   5  15  26  41  81    -40   30  2015-16

In [10]:
table201617 = pd.read_csv('./datasets/2016-17 Championship Table.csv')
table201617.drop(['Attendance','Top Team Scorer', 'Goalkeeper', 'Notes'], axis=1, inplace=True)
table201617['Season'] = "2016-17"
table201617

    Rk            Squad  MP   W   D   L  GF  GA  GDiff  Pts   Season
0    1    Newcastle Utd  46  29   7  10  85  40     45   94  2016-17
1    2         Brighton  46  28   9   9  74  40     34   93  2016-17
2    3          Reading  46  26   7  13  68  64      4   85  2016-17
3    4   Sheffield Weds  46  24   9  13  60  45     15   81  2016-17
4    5     Huddersfield  46  25   6  15  56  58     -2   81  2016-17
5    6           Fulham  46  22  14  10  85  57     28   80  2016-17
6    7     Leeds United  46  22   9  15  61  47     14   75  2016-17
7    8     Norwich City  46  20  10  16  85  69     16   70  2016-17
8    9     Derby County  46  18  13  15  54  50      4   67  2016-17
9   10        Brentford  46  18  10  18  75  65     10   64  2016-17
10  11          Preston  46  16  14  16  64  63      1   62  2016-17
11  12     Cardiff City  46  17  11  18  60  61     -1   62  2016-17
12  13      Aston Villa  46  16  14  16  47  48     -1   62  2016-17
13  14         Barnsley  46  15  13  18  64  67     -3   58  2016-17
14  15           Wolves  46  16  10  20  54  58     -4   58  2016-17
15  16     Ipswich Town  46  13  16  17  48  58    -10   55  2016-17
16  17     Bristol City  46  15   9  22  60  66     -6   54  2016-17
17  18              QPR  46  15   8  23  52  66    -14   53  2016-17
18  19  Birmingham City  46  13  14  19  45  64    -19   53  2016-17
19  20    Burton Albion  46  13  13  20  49  63    -14   52  2016-17
20  21  Nott'ham Forest  46  14   9  23  62  72    -10   51  2016-17
21  22        Blackburn  46  12  15  19  53  65    -12   51  2016-17
22  23   Wigan Athletic  46  10  12  24  40  57    -17   42  2016-17
23  24    Rotherham Utd  46   5   8  33  40  98    -58   23  2016-17

In [11]:
table201718 = pd.read_csv('./datasets/2017-18 Championship Table.csv')
table201718.drop(['Attendance','Top Team Scorer', 'Goalkeeper', 'Notes'], axis=1, inplace=True)
table201718['Season'] = "2017-18"
table201718

    Rk            Squad  MP   W   D   L  GF  GA  GDiff  Pts   Season
0    1           Wolves  46  30   9   7  82  39     43   99  2017-18
1    2     Cardiff City  46  27   9  10  69  39     30   90  2017-18
2    3           Fulham  46  25  13   8  79  46     33   88  2017-18
3    4      Aston Villa  46  24  11  11  72  42     30   83  2017-18
4    5    Middlesbrough  46  22  10  14  67  45     22   76  2017-18
5    6     Derby County  46  20  15  11  70  48     22   75  2017-18
6    7          Preston  46  19  16  11  57  46     11   73  2017-18
7    8         Millwall  46  19  15  12  56  45     11   72  2017-18
8    9        Brentford  46  18  15  13  62  52     10   69  2017-18
9   10    Sheffield Utd  46  20   9  17  62  55      7   69  2017-18
10  11     Bristol City  46  17  16  13  67  58      9   67  2017-18
11  12     Ipswich Town  46  17   9  20  57  60     -3   60  2017-18
12  13     Leeds United  46  17   9  20  59  64     -5   60  2017-18
13  14     Norwich City  46  15  15  16  49  60    -11   60  2017-18
14  15   Sheffield Weds  46  14  15  17  59  60     -1   57  2017-18
15  16              QPR  46  15  11  20  58  70    -12   56  2017-18
16  17  Nott'ham Forest  46  15   8  23  51  65    -14   53  2017-18
17  18        Hull City  46  11  16  19  70  70      0   49  2017-18
18  19  Birmingham City  46  13   7  26  38  68    -30   46  2017-18
19  20          Reading  46  10  14  22  48  70    -22   44  2017-18
20  21           Bolton  46  10  13  23  39  74    -35   43  2017-18
21  22         Barnsley  46   9  14  23  48  72    -24   41  2017-18
22  23    Burton Albion  46  10  11  25  38  81    -43   41  2017-18
23  24       Sunderland  46   7  16  23  52  80    -28   37  2017-18

In [12]:
table201819 = pd.read_csv('./datasets/2018-19 Championship Table.csv')
table201819.drop(['Attendance','Top Team Scorer', 'Goalkeeper', 'Notes'], axis=1, inplace=True)
table201819['Season'] = "2018-19"
table201819

    Rk            Squad  MP   W   D   L  GF  GA  GDiff  Pts   Season
0    1     Norwich City  46  27  13   6  93  57     36   94  2018-19
1    2    Sheffield Utd  46  26  11   9  78  41     37   89  2018-19
2    3     Leeds United  46  25   8  13  73  50     23   83  2018-19
3    4        West Brom  46  23  11  12  87  62     25   80  2018-19
4    5      Aston Villa  46  20  16  10  82  61     21   76  2018-19
5    6     Derby County  46  20  14  12  69  54     15   74  2018-19
6    7    Middlesbrough  46  20  13  13  49  41      8   73  2018-19
7    8     Bristol City  46  19  13  14  59  53      6   70  2018-19
8    9  Nott'ham Forest  46  17  15  14  61  54      7   66  2018-19
9   10     Swansea City  46  18  11  17  65  62      3   65  2018-19
10  11        Brentford  46  17  13  16  73  59     14   64  2018-19
11  12   Sheffield Weds  46  16  16  14  60  62     -2   64  2018-19
12  13        Hull City  46  17  11  18  66  68     -2   62  2018-19
13  14          Preston  46  16  13  17  67  67      0   61  2018-19
14  15        Blackburn  46  16  12  18  64  69     -5   60  2018-19
15  16       Stoke City  46  11  22  13  45  52     -7   55  2018-19
16  17  Birmingham City  46  14  19  13  64  58      6   52  2018-19
17  18   Wigan Athletic  46  13  13  20  51  64    -13   52  2018-19
18  19              QPR  46  14   9  23  53  71    -18   51  2018-19
19  20          Reading  46  10  17  19  49  66    -17   47  2018-19
20  21         Millwall  46  10  14  22  48  64    -16   44  2018-19
21  22    Rotherham Utd  46   8  16  22  52  83    -31   40  2018-19
22  23           Bolton  46   8   8  30  29  78    -49   32  2018-19
23  24     Ipswich Town  46   5  16  25  36  77    -41   31  2018-19

In [14]:
table201920 = pd.read_csv('./datasets/2019-20 Championship Table.csv')
table201920.drop(['Attendance','Top Team Scorer', 'Goalkeeper', 'Notes', 'Last 5'], axis=1, inplace=True)
table201920['Season'] = "2019-20"
table201920

    Rk            Squad  MP   W   D   L  GF  GA  GDiff  Pts   Season
0    1     Leeds United  46  28   9   9  77  35     42   93  2019-20
1    2        West Brom  46  22  17   7  77  45     32   83  2019-20
2    3        Brentford  46  24   9  13  80  38     42   81  2019-20
3    4           Fulham  46  23  12  11  64  48     16   81  2019-20
4    5     Cardiff City  46  19  16  11  68  58     10   73  2019-20
5    6     Swansea City  46  18  16  12  62  53      9   70  2019-20
6    7  Nott'ham Forest  46  18  16  12  58  50      8   70  2019-20
7    8         Millwall  46  17  17  12  57  51      6   68  2019-20
8    9          Preston  46  18  12  16  59  54      5   66  2019-20
9   10     Derby County  46  17  13  16  62  64     -2   64  2019-20
10  11        Blackburn  46  17  12  17  66  63      3   63  2019-20
11  12     Bristol City  46  17  12  17  60  65     -5   63  2019-20
12  13              QPR  46  16  10  20  67  76     -9   58  2019-20
13  14          Reading  46  15  11  20  59  58      1   56  2019-20
14  15       Stoke City  46  16   8  22  62  68     -6   56  2019-20
15  16   Sheffield Weds  46  15  11  20  58  66     -8   56  2019-20
16  17    Middlesbrough  46  13  14  19  48  61    -13   53  2019-20
17  18     Huddersfield  46  13  12  21  52  70    -18   51  2019-20
18  19       Luton Town  46  14   9  23  54  82    -28   51  2019-20
19  20  Birmingham City  46  12  14  20  54  75    -21   50  2019-20
20  21         Barnsley  46  12  13  21  49  69    -20   49  2019-20
21  22     Charlton Ath  46  12  12  22  50  65    -15   48  2019-20
22  23   Wigan Athletic  46  15  14  17  57  56      1   47  2019-20
23  24        Hull City  46  12   9  25  57  87    -30   45  2019-20

In [15]:
table = pd.concat([table201415, table201516, table201617, table201718, table201819, table201920])
table.to_csv('Championship Table Consolidated.csv', index=False)